---
version: '3'

volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    restart: always
    image: d213honeynet/cowrie:version1
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var

  dionaea:
    image: d213honeynet/dionaea:version1
    restart: always
    volumes:
      - /home/ubuntu/dionaea/etc/dionaea:/opt/dionaea/etc/dionaea
      - /home/ubuntu/dionaea/var/log:/opt/dionaea/var/log/dionaea
      - /home/ubuntu/dionaea/var/lib:/opt/dionaea/var/lib/dionaea
    ports:
      - "21:21" #Ftp
      - "42:42" #
      - "69:69/udp" #Tftp
      - "135:135" #MS DCE RPC
      - "443:443" #HTTPS
      - "445:445" #SMB
      - "1433:1433" #MS SQL Server
      - "1723:1723" #PPTP
      - "1883:1883" #MQTT
      - "1900:1900"
      - "3306:3306" #MySQL
      - "5060:5060" #sip
      - "5060:5060/udp" #sip
      - "5061:5061" #sip
      - "11211:11211" #Memcached

  glastopf:
    image: d213honeynet/glastopf:version1
    restart: always
    volumes:
      - /home/ubuntu/glastopf:/opt/myhoneypot
    ports:
      - "80:80" #http
